if ~isfield(EEG.etc,'wininterp') || isempty(EEG.etc.wininterp)
		warning(['No single-trial channels have been marked for interpolation.',...
					'Make sure to use the Mark menu option and then the Interpolate option after marking.'])
		return;
end
if ~exist('nEEG','var')
		warning('No single-trial channels have been interpolated. Make sure to use the Interpolate menu option after Marking.')
		return;
end

if ~isempty(EEG.reject.rejmanual)
	wj = EEG.etc.wininterp;
	wj(wj(:,5)~=.783,:) = [];

	ie_eegplot(nEEG.data,...
			'data2', EEG.data,...
			'events', EEG.event,...
			'srate', EEG.srate,...
			'limits', [EEG.xmin EEG.xmax]*1000,...
			'winrej', wj,...
			'wincolor', [1 1 .783],...
			'title', ['Plot before (red) and after (blue) interpolation results -- ', EEG.setname],...
			'eloc_file', EEG.chanlocs);
else
	ie_eegplot(nEEG.data,...
			'data2', EEG.data,...
			'events', EEG.event,...
			'srate', EEG.srate,...
			'limits', [EEG.xmin EEG.xmax]*1000,...
			'title', ['Plot before (red) and after (blue) interpolation results -- ', EEG.setname],...
			'eloc_file', EEG.chanlocs);
end