function EEG = pop_interp_epoch(EEG)
	if ~isfield(EEG.etc,'wininterp')
		wj = []; 
	else
		wj = EEG.etc.wininterp; 
	end

	% this helps integrate with native functionality marked whole epcohs
	if ~isempty(EEG.reject.rejmanual)
		fi = find(EEG.reject.rejmanual);
		strtstp = [0 EEG.pnts-1]+(fi-1)'*EEG.pnts;
		strtstp(strtstp==0) = 1;
		wcol = [strtstp, repmat([1 1 .783], length(fi), 1), zeros(length(fi), EEG.nbchan)];
		wj = [wj; wcol];
		wj = unique(wj, 'rows');
	end

	eegplot(EEG.data,...
		'command', 'cb_popinterp',...
		'events', EEG.event,...
		'srate', EEG.srate,...
		'limits', [EEG.xmin EEG.xmax]*1000,...
		'eloc_file', EEG.chanlocs,...
		'winrej', wj,...
		'wincolor', [1 1 .783],...
		'butlabel', 'UPDATE MARKS',...
		'title', ['Right-click to mark channels for interpolation within desired epochs -- ', EEG.setname],...
		'ctrlselectcommand', { 'cb_ctrlcmd;', '', '' }...
		);
