function EEG = pop_mark(EEG)
  if ~isfield(EEG.etc, 'wininterp')
    EEG.etc.wininterp = [];
  end
	if ~isempty(EEG.reject.rejmanual)
		EEG = update_wininterp_with_rejmanual(EEG);
	end

	ie_eegplot(EEG.data,...
		'command', 'cb_updatemarks',...
		'events', EEG.event,...
		'srate', EEG.srate,...
		'limits', [EEG.xmin EEG.xmax]*1000,...
		'eloc_file', EEG.chanlocs,...
		'winrej', EEG.etc.wininterp,...
		'wincolor', [1 1 .783],...
		'butlabel', 'UPDATE MARKS',...
		'title', ['Right-click to mark channels for interpolation within desired epochs -- ', EEG.setname],...
		'ctrlselectcommand', { 'cb_ctrlcmd;', '', '' }...
		);

% [1 1 1] red single channel trial
% [1 1 .783] whole epoch
% eegplot reject via inspection function goes from 1 to EEG.pnts but
% switches to 0 to EEG.pnts-1